disclaimer <- function(...){

  div(
    class = "modal",
    tabindex="-1",
    id = "disclaimer",
    div(
      class = "modal-dialog bg-white",
      # Header
      div(
        class = "modal-header",
        h5(class = "modal-title", "Disclaimer"),
        tags$button(
          type = "button",
          class = "btn-close",
          `data-bs-dismiss` = "modal",
          `aria-label` = "Close"
        )
      ),
      # Body
      div(
        class = "modal-body",
        p("This tool is provided for general information only."),
        p("The State of Victoria provides no warranty or guarantee and makes no representation that the information contained in this tool is current, accurate, complete, without flaw of any kind or is suitable for your particular purposes."),
        p("You must not rely on this tool for any general or specific purpose, including as a statement of government policy (except where clearly stated). You are responsible for assessing whether the information generated by this tool is accurate, complete or suitable and you should seek your own independent professional advice."),
        p("To the extent permitted by law, the State of Victoria disclaims liability for any error, loss, damages, costs or other consequence caused by the use or reliance on information contained in this tool. The State of Victoria reserves the right to amend or withdraw this publication as required and without notice.")
      ),
      div(
        class = "modal-footer",
        tags$button(
          type = "button",
          class = "btn btn-secondary",
          `data-bs-dismiss`="modal",
          "Close"
        )
      )
    )
  )
}
